### ISSUE TITLE
Where do I put the Netbox token to write to Netbox?

### ISSUE THREAD

**Issue by mariano-daniel** [Cennepal/Netbox-IP-Scanner-2#1]
First of all thanks for the re-write of the code! But my question being, how do I make it run? The previous repo had the inputs for the Netbox info in the .py file. Should I sort of Merge them? I'm sorry I'm confused!

Thanks again for the contribution!

**Comment by Cennepal** [comment]
Well, this one doesn't actually use the pynetbox API and instead uses the built-in models that come with netbox. Which means that if you add it to netbox, it works internally without having to hardcode credentials or URLs.

**Comment by Cennepal** [comment]
Also just a quick heads up. On line 47 I set the ping timeout to 20 millis due to how fast our internal network is, but you may have to set it higher if stuff doesn't respond fast enough. Generally, a 1 second timeout is the slowest, but the surest.

**Comment by mariano-daniel** [comment]
Thanks! But I ran into an error now:

```
/opt/netbox/netbox# python3 netbox_ipscanner_2.py 
Traceback (most recent call last):
  File "/opt/netbox-4.0.7/netbox/netbox_ipscanner_2.py", line 1, in <module>
    from extras.scripts import Script
  File "/opt/netbox-4.0.7/netbox/extras/scripts.py", line 9, in <module>
    from django import forms
ModuleNotFoundError: No module named 'django'

```

There's something I'm doing wrong and can't figure out what. I googled but found not the same scenario. :/

**Comment by Cennepal** [comment]
> Thanks! But I ran into an error now:
> 
> ```
> /opt/netbox/netbox# python3 netbox_ipscanner_2.py 
> Traceback (most recent call last):
>   File "/opt/netbox-4.0.7/netbox/netbox_ipscanner_2.py", line 1, in <module>
>     from extras.scripts import Script
>   File "/opt/netbox-4.0.7/netbox/extras/scripts.py", line 9, in <module>
>     from django import forms
> ModuleNotFoundError: No module named 'django'
> 
> ```
> 
> There's something I'm doing wrong and can't figure out what. I googled but found not the same scenario. :/

Because the script is not an external one. It works from **within** Netbox. Which means uploading it via Customization > Scripts and executing it from within netbox.

**Comment by mariano-daniel** [comment]
Oh maaannn sorry! You meant from the GUI not the Netbox directory! Sorry I misunderstood! I am starting with Netbox and was only used to importing them from the CLI.

Now I get it, and actually I understand why so many other scripts don't work! 🫠 Thank you so much!
