### ISSUE TITLE
ping3 PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by gaows20** [Cennepal/Netbox-IP-Scanner-2#2]
ping must run as root.

log:
An exception occurred: PermissionError: [Errno 13] Permission denied

Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.12/site-packages/ping3/__init__.py", line 281, in ping
    sock = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_ICMP)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 233, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox-4.1.1/netbox/extras/jobs.py", line 45, in run_script
    script.output = script.run(data, commit)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.1/netbox/scripts/netbox_ipscanner_2.py", line 52, in run
    is_pingable = ping(str(ip), timeout=is_pingable_ms_to, unit='ms')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/ping3/__init__.py", line 83, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.12/site-packages/ping3/__init__.py", line 285, in ping
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_ICMP)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 233, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied

**Comment by Cennepal** [comment]
If this is running within docker, you need to give the container sufficient network network capability permissions for it to work, like CAP_NET_RAW.

**Comment by gaows20** [comment]
not within docker

**Comment by Cennepal** [comment]
> not within docker

Still, most likely the user running the binary doesn't have raw network permissions. I have encountered this issue before, but I sadly can't recall anymore what solved the issue. However I did find this link which should give some pointers on how to add capabilities to the binary for non-root users:

https://stackoverflow.com/questions/37512291/how-is-ping-for-non-root-user-implemented-on-linux-distros/37518095

**Comment by gaows20** [comment]
ths！resolved.
Allow non root users to use ping:
# sysctl net.ipv4.ping_group_range="0 2147483647"
